---
- file:
    path: "{{ item }}"
    owner: jenkins
    group: jenkins
    mode: 0755
    state: directory
  with_items: jenkins_directories

- shell: >
    curl -L https://updates.jenkins-ci.org/update-center.json | sed '1d;$d' > /var/lib/jenkins/updates/default.json
    creates=/var/lib/jenkins/updates/default.json

- file:
    path: /var/lib/jenkins/updates/default.json
    owner: jenkins
    group: jenkins
    mode: 0755
